name: build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        commit:
          - c1d637433e3b3f9012b226c2c9125c494b470ae6
          - 9700fc847a39e98dfb7bd85331b5206641050e04
          - master
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Download Eigen
        run: |
          git clone https://gitlab.com/libeigen/eigen.git
      - name: Install Eigen
        run: |
          git checkout ${{ matrix.commit }}
          cmake -Bbuild -S. \
            -D CMAKE_INSTALL_PREFIX="$PWD/../install-eigen" \
            -D BUILD_TESTING=Off \
            -D CMAKE_Fortran_COMPILER=""
          cmake --build build
          cmake --install build
        working-directory: eigen
      - name: Build example project
        run: |
          cmake -Bbuild -S. \
            -D Eigen3_DIR="$PWD/install-eigen/share/eigen3/cmake"
          cmake --build build
